sudo: required

language: generic

services:
  -docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t rmswjdtn/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true rmswjdtn/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-reac애t-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-820804510581"
  bucket_path: "docker-react-app"
  on:
    branch: master


  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY